### ISSUE TITLE
Codeclimate ready?

### ISSUE THREAD

**Issue by freiden** [fazibear/codeclimate-credo#1]
Hi @fazibear,
You're project seems very interesting and I would like to include it on my codeclimate projects.
Did you apply to the Codeclimate developer Program to make it available on their plaform or are you planning to?

Thanks by advance for your answer.

**Comment by fazibear** [comment]
Yes. I'm working on this and other one engine with code climate team to make it public. I'll do my best to make it available asap. So stay truned. Thanks for your interest.

**Comment by freiden** [comment]
Hi @fazibear any update the codeclimate integration? If you need help about maybe I can give you some?

**Comment by fazibear** [comment]
Things are happening. Codeclimate guys testing it right now.

**Comment by dblandin** [comment]
Hey @freiden,

I just released @fazibear's codeclimate-credo engine to codeclimate.com and our CLI under a beta channel if you want to help test it out!

You can enable the engine with the following `.codeclimate.yml` additions:

``` yaml
---
engines:
  credo:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.ex"
  - "**.exs"
```

**Comment by freiden** [comment]
@dblandin Can I use this engine on a on-premise version?

**Comment by dblandin** [comment]
@freiden Yes! While not mentioned in the release notes, the beta channel for the Credo engine is available on Code Climate: Enterprise as of version 1294, released on October 6th.

**Comment by freiden** [comment]
@dblandin & @fazibear It looks like it works, I need to customize my credo settings but everything looks good.
Thanks.

**Comment by fazibear** [comment]
@freiden You can customize it with `.credo.exs` file.

**Comment by freiden** [comment]
Thanks @fazibear I'm looking at it right now but it seems more complex to set it up to the style guide I'm following than I was expecting (I'm more used to something like Rubocop :)).

**Comment by dblandin** [comment]
@freiden If you haven't checked it out already, credo has some documentation on that [here](https://github.com/rrrene/credo#configuration-via-credoexs) and you can reference [Credo's own .credo.exs](https://github.com/rrrene/credo/blob/master/.credo.exs) as a complete example.

It looks like you can reference each individual check to see what parameters are supported. For example, [here are the supported parameters](https://github.com/rrrene/credo/blob/master/lib/credo/check/design/duplicated_code.ex#L23-L26) for the `DuplicatedCode` check:

``` elixir
    params: [
      mass_threshold: "The minimum mass which a part of code has to have to qualify for this check.",
      nodes_threshold: "The number of nodes that need to be found to raise an issue."
    ]
```
